language: rust
rust:
 - stable
 - beta

install:
 - rustup install nightly               # using nightly features of rustfmt

before_script:
 - rustup component add clippy
 - rustup component add rustfmt --toolchain nightly
 - if [ ! -f data/sets.json ]; then ./download_data.sh; fi

script:
 - cargo check
 - cargo test
 - cargo clippy -- -D warnings
 - cargo +nightly fmt --all -- --check

before_deploy:
 - cargo doc --no-deps --lib
 - >
   if [ -n "$TRAVIS_TAG" ]; then
     cargo build --release
     mkdir dofus-generate-stuff \
       && cp target/release/stuffer dofus-generate-stuff \
       && cp -r data examples dofus-generate-stuff
     tar -czf dofus-generate-stuff.tar.gz dofus-generate-stuff
   fi

cache:
  directories:
   - data

deploy:
 - provider: pages
   local_dir: target/doc
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
     branch: master
     condition: $TRAVIS_RUST_VERSION = stable
 - provider: releases
   api_key: $GITHUB_TOKEN
   file: dofus-generate-stuff.tar.gz
   skip_cleanup: true
   on:
     tags: true
     repo: remi-dupre/dofus-generate-stuff
     condition: $TRAVIS_RUST_VERSION = stable
