language: rust
rust:
 - stable
 - beta

install:
 - rustup install nightly               # using nightly features of rustfmt

before_script:
 - rustup component add clippy
 - rustup component add rustfmt --toolchain nightly
 - if [ ! -d data/sets.json ]; then ./download_data.sh; fi

script:
 - cargo check
 - cargo clippy -- -D warnings
 - cargo +nightly fmt --all -- --check

before_deploy:
 - cargo build --release
 - mkdir dofus-generate-stuff
    && cp target/release/dofus-generate-stuff dofus-generate-stuff
    && cp -r data dofus-generate-stuff
 - tar -czf dofus-generate-stuff.tar.gz dofus-generate-stuff

cache:
  directories:
   - data

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
   - dofus-generate-stuff.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: remi-dupre/dofus-generate-stuff
    condition: $TRAVIS_RUST_VERSION = stable
